language:
    - python

python:
    - "3.4"

services:
    - mysql

install:
    # Build/test dependencies
    - pip install -r requirements.txt

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('7uy33HZ5') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
    - python src/sql_module/test_unit_sql.py
